apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aetheris-auth-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: aetheris-auth
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
